CREATE TABLE IF NOT EXISTS breadth (
  ts_ist TIMESTAMPTZ PRIMARY KEY,
  adv INTEGER NOT NULL,
  dec INTEGER NOT NULL,
  unchanged INTEGER
);
CREATE TABLE IF NOT EXISTS vix (
  ts_ist TIMESTAMPTZ PRIMARY KEY,
  value NUMERIC NOT NULL
);
