    """Baselines service
    NOTE: Stub module. Add real logic later.
    """

def capture_fut_oi_baseline(symbol: str): ...
def get_fut_oi_baseline(symbol: str): ...
def capture_ib_snapshot(symbol: str): ...
def get_ib_snapshot(symbol: str): ...

