    """Refs & levels
    NOTE: Stub module. Add real logic later.
    """

def compute_session_refs(symbol: str) -> dict: ...
def compute_ib(symbol: str) -> dict: ...
def adr_lookback(symbol: str, n: int = 14) -> float: ...
def pivots_cpr(symbol: str) -> dict: ...

