    """Validators
    NOTE: Stub module. Add real logic later.
    """

def freshness_ok(f: dict) -> bool: ...
def chain_coverage_ok(chain: list) -> bool: ...
def bar_complete_ok(bar: dict) -> bool: ...

