    """Greeks & IV regime
    NOTE: Stub module. Add real logic later.
    """

def expected_move(chain_rows: list[dict]) -> float: ...
def gamma_regime(chain_rows: list[dict]) -> str: ...
def skew_tag(chain_rows: list[dict]) -> str: ...

