    """Price Action tools
    NOTE: Stub module. Add real logic later.
    """

def structure_hh_hl(bars: list[dict]) -> str: ...
def detect_bos(bars: list[dict]) -> bool: ...
def detect_choch(bars: list[dict]) -> bool: ...
def detect_sweep(levels: dict, bars: list[dict]) -> dict: ...
def detect_box(bars: list[dict]) -> dict: ...

