    """Risk & RR tools
    NOTE: Stub module. Add real logic later.
    """

def rr_preview(entry: float, sl: float, tp: float) -> dict: ...
def sl_viability(spread: float, atr: float) -> bool: ...
def level_proximity(distance_em: float, min_required: float = 0.3) -> bool: ...

