    """VWAP & Trend tools
    NOTE: Stub module. Add real logic later.
    """

def vwap_session(bars: list[dict]) -> dict: ...
def price_vs_vwap(price: float, vwap: float) -> str: ...
def slope_5m(bars: list[dict]) -> str: ...
def slope_15m(bars: list[dict]) -> str: ...

