    """Volume tools
    NOTE: Stub module. Add real logic later.
    """

def relative_volume_5m(symbol: str) -> float: ...
def volume_spike(bars: list[dict]) -> bool: ...
def session_profile(bars: list[dict]) -> dict: ...

