    """Breadth/VIX repo
    NOTE: Stub module. Add real logic later.
    """

def upsert_breadth(rows: list[dict]): ...
def upsert_vix(rows: list[dict]): ...
def latest_breadth() -> dict: ...
def latest_vix() -> dict: ...

