cadence:
  ohlcv5m: 60
  oi: 90
  chain: 150
  breadth_vix: 300
  context_ib: 45
  context_mid: 75
  context_late: 60

freshness_sla_s:
  ohlcv5m: 90
  oi: 120
  chain: 180
  breadth: 300
  vix: 300

session:
  timezone: "Asia/Kolkata"
  ib_start: "09:15"
  ib_end: "10:15"
  no_new_after: "14:45"
  eod_exit: "15:20"

risk:
  rr_min: 1.2
  wall_min_distance_em: 0.3
  max_positions: 2

models:
  default: "gpt-4o-mini"
  escalate: "gpt-4o"
  escalate_if_conf_lt: 60

market:
  tz: "Asia/Kolkata"
  provider: "kite"
  timeouts:
    http: 6
    quote: 3
  retries:
    max_attempts: 3
    base_delay_ms: 250
  cache:
    instruments_ttl_sec: 86400
  ohlcv:
    tfs: ["5m", "15m", "1d"]
    bar_complete_delay_s: 10
  options:
    quote_chunk: 200
    chunk_pacing_sec: 0.20
    risk_free_rate_annual: 0.065
    dividend_yield_annual: 0.0
    strikes_span: 12
    expiries_max: 3
    index_symbols:
      - "NIFTY 50"
      - "NIFTY BANK"
  breadth:
    enabled: true
  vix:
    enabled: true
